name: build-test-push-toys
on:
  workflow_dispatch:
#  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and export
      uses: docker/build-push-action@v5
      with:
        context: ./cicd
        file: ./cicd/Dockerfile
        tags: toys-robust:latest, ${{ vars.USERNAME }}/toys-robust:latest
        outputs: type=docker,dest=/tmp/image.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: toys-robust
        path: /tmp/image.tar  # downloads the image (named image.tar) to the /tmp dir
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
#    # 1. download image and run it in a container
    - name: Download artifact
      uses: actions/download-artifact@v4  # downloads all artifacts
      with:
        name: toys-robust
        path: /tmp
    - name: Verify downloaded artifact
      run: ls -l /tmp
    - name: Load Docker toys-robust tar image from previous job (load is for tar images)
      run: docker load --input /tmp/image.tar
    - name: check toys-robust image is loaded
      run: docker image ls
    - name: Pull mongo image from dockerhub
      run: docker pull mongo:latest
    - name: run mongo in container
      run: docker run -d -p 27017:27017 mongo:latest --name mongo mongo:latest
    - name: wait for Mongo to be ready
      run: |
        timeout 30 sh -c 'until docker exec mongo mongosh --eval "db.adminCommand({ping: 1})" > /dev/null 2>&1; do sleep 1; done'
        echo "MongoDB is ready!"
    - name: run toys-robust image in container
      run: docker run -p 8000:80 toys-robust &
    - name: Check container is running
      run: docker ps
#    # 2. set up python and pytest environment
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest # not using "yet" lint checker like ruff
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#      # 3. run pytest tests and upload the results to GH_test_results
    - name: check for pytest directory
      run: |
        ls -l
    - name: Test with pytest  # additionally use ruff or other lint checkers
      run: |
        cd pytest-code
        pytest -v test-toys.py > test_results.txt
    - name: upload test results
      if: always()  # always perform this step even if tests fail, to see results
      uses: actions/upload-artifact@v4
      with:
        name: GH_test_results
        path: pytest-code/test_results.txt
#      The following steps will only execute if tests succeeded
#      # 4. Push images to DockerHub
    - name: Set DATE
      run: echo "DATE=$(date -I)" >> $GITHUB_ENV
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_COURSE_USERNAME }}
        password: ${{ secrets.DOCKER_COURSE_PASSWORD }}
    - name: push image with "latest" and date tags to DH
      run: |
        docker push ${{ secrets.DOCKER_COURSE_USERNAME }}/toys
        docker tag ${{ secrets.DOCKER_COURSE_USERNAME }}/toys \
        ${{ secrets.DOCKER_COURSE_USERNAME }}/toys:${{ env.DATE }}
        docker push \
        ${{ secrets.DOCKER_COURSE_USERNAME }}/toys:${{ env.DATE }}