name: Build and push toys Docker image
on:
# comment out next line so do not build on each push of other workloads.  Uncomment when using
#  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Log in to Docker Hub
      # username/password is the username/pw of my DockerHub teaching acct
      uses: docker/login-action@v3
      with:
        username: ${{ vars.USERNAME }}
        password: ${{ secrets.PASSWORD }}
    - name: Show workspace
      run: |
        echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
        pwd
        ls -la
    - name: Set DATE
      run: |
        echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Verify DATE
      run: |
        echo "DATE is: '${DATE}'"
    - name: Build the Docker image
      run: |
        docker build ./cicd/ --tag ${{ vars.USERNAME }}/toys-robust
        docker tag ${{ vars.USERNAME }}/toys-robust ${{ vars.USERNAME }}/toys-robust:${{ env.DATE }}
    - name: Push to Docker Hub
      run: |
        docker push ${{ vars.USERNAME }}/toys-robust
        docker push ${{ vars.USERNAME }}/toys-robust:${{ env.DATE }}
