name: Build and push toys Docker image
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ vars.DOCKER_COURSE_USERNAME }}
          password: ${{ secrets.DOCKER_COURSE_PASSWORD }}
    - name: Set DATE
      run: "DATE=$(date +'%Y-%m-%d')"
    # run: echo "DATE=$(date -I)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: |
        docker build . --file cicd/Dockerfile.toys --tag \
        ${{ vars.DOCKER_COURSE_USERNAME }}/toys
      # docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        docker tag ${{ vars.DOCKER_COURSE_USERNAME }}/toys \
        ${{ vars.DOCKER_COURSE_USERNAME }}/toys:${{ env.DATE }}
    - name: Push to Docker Hub
      run: |
        docker push ${{ vars.DOCKER_COURSE_USERNAME }}/toys
        docker push \
        ${{ vars.DOCKER_COURSE_USERNAME }}/toys:${{ env.DATE }}
